name: appsmith-cd  # Workflow name

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  deploy-appsmith:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - run: "curl -f --location --request POST https://app.appsmith.com/api/v1/git/deploy/app/65f14c735?branchName=master --header 'Authorization: Bearer ${{ secrets.APPSMITH_CD_KEY }}'"
