name: appsmith-cd  # Workflow name

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  deploy-appsmith:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - run: "curl --location --fail-early --request POST https://smartforce.demo.appsmith.com/api/v1/git/applications/696e75c9f5c31a2d63a55cdb/deploy?refName=master --header 'Authorization: Bearer ${{4e0350ef109e67aeaa2b5ea993c13e81eb276d4759d2a2f39ca20d720d2281b8fec94a584e0d3a6937b3b7ac05f3cfd8cb20ca6e8185d7f7484d3c12c80230bba6bd0ca9709b27f50f88ac4429b1f3f16d5ad6e7ee721a6de3c49cda5816382dd6fbd2d1da84a22544b354872891c2c16f6483f3ddff6ced2535be68167b1d78ae83c5273fd014c5592711fe58e69d2ee5f2470099c3b3190f702ff040acf52ec1b555b8ac0dec0877bb44bc368bfa21ebdbb293b4fd2dd89c8ecf1a2f67e20f78efffc1efb4f1edea6fd30c6b70e57eab0350aa881ba8c3075e0ab9adb3cf1e'}}'"
